# Schema for the configuration files of the Rinrin theme.

rinrin.settings:
  type: theme_settings
  label: 'rinrin settings'
  mapping:
    third_party_settings:
      type: mapping
      label: 'Third party settings'
      mapping:
        shortcut:
          type: mapping
          label: 'Shortcut'
          mapping:
            module_link:
              type: boolean
              label: 'Module Link'
    mobile_menu_all_widths:
      type: integer
      label: 'Mobile menu all widths'
      constraints:
        Choice:
          # @see rinrin_preprocess_html()
          # Set to 1 to enable the mobile menu toggle at all widths.
          choices:
            - 0
            - 1
    site_branding_bg_color:
      type: string
      label: 'Site branding background color'
      constraints:
        Choice:
          # @see rinrin_form_system_theme_settings_alter()
          choices:
            - "default"
            - "gray"
            - "white"
    base_primary_color:
      type: color_hex
      label: 'Base Primary Color'
